services:
  server:
    image: ${IMAGE}
    healthcheck:
      test: ["CMD", "redis-cli", "--insecure", "--tls", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  sut:
    image: ${IMAGE}
    depends_on:
      server:
        condition: service_healthy
    entrypoint: ["/bin/true"]
