name: Local Build & Test
on:
  - push
  - pull_request
env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/redis
  BASE_IMAGE: redis
jobs:
  build-only:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: alpine
            version: "7-alpine"

          - distro: debian
            version: "7"

          - distro: debian
            version: latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build --rm -f ${{ matrix.distro }}.Dockerfile
          --build-arg base_image=${{ env.BASE_IMAGE }}:${{ matrix.version }}
          --tag ${{ env.IMAGE }}:${{ matrix.version }}
          .

      - name: Install Docker Compose
        uses: withlogicco/setup-compose-cli@v1

      - name: Test alpine image
        env:
          IMAGE: ${{ env.IMAGE }}:${{ matrix.version }}
        run: docker compose -f docker-compose.test.yml run sut
